### ISSUE TITLE
Focus is "reset" when selecting a text on IE

### ISSUE THREAD

**Issue by romgere** [focus-trap/focus-trap#115]
On IE when a focus trap is activated, an element focused & a text is selected, focus trap "detects" a focus change (outside of the trap) & force the focus on the first element.

Here is my test on the focus-trap demo page : 
![focus_ie](https://user-images.githubusercontent.com/13900970/83637689-4b061500-a5a8-11ea-9f8d-afe91b902417.gif)

Same test on Chrome : 
![focus_chrome](https://user-images.githubusercontent.com/13900970/83637853-8a346600-a5a8-11ea-99c9-866c95e5977c.gif)

From what I see, IE fire an "additional" `focusIn` event on document which cause this behavior...

**Comment by jmmccasland-hint** [comment]
I had a similar issue on Safari when opening a modal that would dynamically load a set of focusable elements. I'm assuming since the elements didn't exist on mount, each time I'd try to click one, focus would get sent back to the first el.
Setting tabindex="-1" on the drawer and setting the `initialFocus` prop to first el in tandem seemed to solve the issue for me.

Best of luck!

**Comment by stefcameron** [comment]
I'm open to a fix if there's truly a bug here, but I don't have access to IE to test it out, and I don't fully understand the problem based on the description. I'd need someone with IE to submit a PR.

**Comment by stefcameron** [comment]
Closing very old issues. There have been a lot of improvements to the library (and tabbable) since I took over in July 2020, and this may be fixed now. If it's still an issue with the current release, feel free to re-open.
