### ISSUE TITLE
Fallback focus is not selected in the case of absence of initial focus element

### ISSUE THREAD

**Issue by konradr33** [focus-trap/focus-trap#1218]
Hi, 
I'm currently struggling with the situation that after creating a focus trap, it wants to focus on a certain element at the start (I use `initialFocus`). 
This element does not always exist. In this case, I wanted to use `fallbackFocus`. 
However, testing this case and reviewing the code I come to the conclusion that this does not work as I thought. 
In `getInitialFocusNode` the element to focus is retrieved by `let node = getNodeForOption('initialFocus')`. However, `getNodeForOption` in the absence of such an element throws an error `.... refers to no known node`. In my opinion, the `fallbackFocus` element should be focused in this scenario, but we don't get to that point in the code. Do I understand this behaviour correctly, or perhaps it works correctly?
I can create a PR if needed, or explain in more detail.

**Comment by stefcameron** [comment]
Hi @konradr33, thanks for reaching out about this. A few questions for you:

- When you say, "this element does not always exist", do you mean in some cases it _never_ exists, or in some cases, there's a delay before it exists?
    - Have you considered the `checkCanFocusTrap` option...?
- The [getNodeForOption](https://github.com/focus-trap/focus-trap/blob/master/index.js#L233) will only throw "refers to no known node" when the given option's value (`initialFocus` in this case) is a `string`, which means it's a selector, and the selector refers to no known node (evaluates to `null`).
    - Are you seeing something different on your end when your code runs?
    - What value are you setting on the `initialFocus` option?
- [getInitialFocusNode](https://github.com/focus-trap/focus-trap/blob/master/index.js#L269) will eventually fall back to the `fallbackFocus` option after a couple of default fallback possibilities have been exhausted.
    - Perhaps you aren't reaching this (line 287) because you're hitting line 261 as a result of the value you're setting on the `initialFocus` option?

**Comment by konradr33** [comment]
To answer the questions.
- `This element does not always exist` i in my case means that the element will exist from the beginning or not at all. The `checkCanFocusTrap` does not apply here.
- For `initialFocus` I use the string value as a selector with the css class.
The result is `'initialFocus' as selector refers to no known node` error.
- I think the code doesn't get to this fallback, here is how I understand the code to work
The `getInitialFocusNode` is supposed to retrieve the node that should receive the focus. In my case, `initialFocus` has a string value for the selector of an element that doesn't exist, and `fallbackFocus` on another element.
When fetching a node in `getNodeForOption` (line 258) selector is applied, null is returned. Since it is null, an error is thrown (`'initialFocus' as selector refers to no known node`). In `getInitialFocusNode` (line 270) there is no `try catch` further code probably won't execute - the `fallbackFocus` from line 287 is never returned.

**Comment by stefcameron** [comment]
@konradr33 Thank you for your answers! I think you've uncovered a bug here with the interplay between the `initialFocus` option and the `fallbackFocus` behavior/option. `getInitialFocusNode()` should have a way to call `getNodeForOption('initialFocus')` such that the selector variant is allowed to result in `undefined` if `doc.getSelector()` returns `null` when there's no match instead of throwing that "selector refers to no known node" exception.

It looks like `Document.querySelector` does throw an exception of its own if the selector's syntax is invalid (as opposed to addressing a non-existent node), which is a good thing because you'd get a more meaningful exception in that case. So perhaps in this case, we should wrap `doc.querySelector()` in a `try..catch` and, if it throws, regardless of the option to allow not finding a node, throw the "selector refers to no known node" error and append the reason, that being the `error.message` the API call threw.

That's what I'd propose doing, along with a couple of new tests to support it.

Do you have other ideas/suggestions on how to fix it?

Would you feel up to making a PR for it?

**Comment by stefcameron** [comment]
@konradr33 Not trying to push/rush, just making sure we aren't waiting on one another. By your 👍 reaction on my previous comment, I assumed that meant you were going to work on a PR. Was my understanding correct?

**Comment by konradr33** [comment]
Hi, you understand correctly. I will come back to the issue when I find free time. Is it a problem to keep the issue open longer?

**Comment by stefcameron** [comment]
> Hi, you understand correctly. I will come back to the issue when I find free time. Is it a problem to keep the issue open longer?

Sounds good. It doesn't look like this issue is affecting a lot of people so we can keep it open for a while longer. I'll check back in a few weeks. Thank you for your willingness to make a PR for it. It'll be very helpful! LMK if you have trouble getting started with the repo.

**Comment by stefcameron** [comment]
@konradr33 FYI, I decided to take a crack at this myself since I want to fix the problem and get rid of this lingering issue. My work so far is on the `fallback-fix` branch. Still WIP.

**Comment by stefcameron** [comment]
@all-constributors add @konradr33 for bug

**Comment by stefcameron** [comment]
@all-contributors add @konradr33 for bug
