### ISSUE TITLE
First focusable element inside a Shadow DOM

### ISSUE THREAD

**Issue by bakura10** [focus-trap/focus-trap#1252]
Hi !

I've read the documentation and found this note:

```
Tabbing will work as expected with trickier, less predictable elements — like iframes, shadow trees, audio and video elements, etc. — as long as they are between more predictable elements (that is, if they are not the first or last tabbable element in the trap).
```

Unfortunately, this is exactly the position I'm facing. I have a modal where the close button (the first focusable element) is within a shadow DOM, while the rest is inside a light DOM, here is a simplified markup:

```
<x-drawer>
  <#shadow-root>
     <button>Close</button>
     // Other stuff
  </#shadow-root>

  // The rest of the content
</x-drawer>
```

When the library trap the focus it puts the focus on the first focusable element in the light dom. If I do a Shift + Tab to go back, the close button in the shadow DOM is properly focused, a sign that Focus Trap is correctly able to find the element. It is just never focused first.

We're having a customer of our that is complaining about that, but could not find any workaround (removing the shadow dom is _not_ a possibility here). I've tried to play with various tabbable options but impossible to find a workaround.

Does anyone have found a solution around that, or would it be possible to update Tabbable to make this use case work?

Thanks.

**Comment by stefcameron** [comment]
@bakura10 Have you tried using the [tabbableOptions.getShadowRoot](https://github.com/focus-trap/tabbable?tab=readme-ov-file#getshadowroot-option) option to make sure your shadow root is found? Although the fact you can tab backward to it seems to indicate that it is found... 🤔 

Have you also tried the [initialFocus](https://github.com/focus-trap/focus-trap?tab=readme-ov-file#createoptions) option?

If nothing seems to work, I would need a code sandbox repro so I can test it myself, but it'll probably take me a while to get to this. I'm pretty swamped at the moment.

Otherwise, I'd welcome a PR if you can find the issue and propose a fix.

**Comment by bakura10** [comment]
Hi @stefcameron ,

Thanks for the answer. Unfortunately I've tried those two options but they are not working. As said it seems to be the expected behavior, as this is what is written in the doc of FocusTrap (emphasize is mine):

Tabbing will work as expected with trickier, less predictable elements — like iframes, shadow trees, audio and video elements, etc. — as long as they are between more predictable elements (that is, if they are not the **first or last tabbable element in the trap**).

If the element in the shadow dom is in second position (so first focusable element is in light dom and second element is in shadow dom) it works properly, which confirms FocusTrap is able to find the node. What was the reason behind the limitation of "first or last" ?

I will try to further read the code of the library to see if I can find the root cause of this!

**Comment by bakura10** [comment]
@stefcameron here is a minimum reproduction case: https://codepen.io/bakura10/pen/JjQVPxj?editors=1111

I've done various attempts (without the getTabbableOptions, with it...) but I could not make it working so that the first button (in the shadow root) is focused first.

**Comment by stefcameron** [comment]
@bakura10 Thanks for the Codepen, that's very helpful. I think what you're dealing with here is a browser issue where the first button, while focused, is not rendered as focused by the browser (Chrome, anyway). Chrome has this weird way of showing focus (or not, depending) when it comes to the shadow DOM.

When focusing an element in a shadow, it'll show as focused not only it, but its shadow root container as well, even though it (i.e. the button -- the __first__ button in this case -- has focus).

This is better illustrated than written, so here's your original Codepen, but with `onclick` events added to both buttons, the `tabbablOptions.getShadowRoot` property fixed, and a `*:focus` selector added to highlight whatever element currently has focus: https://codepen.io/stefcameron/pen/qBedyvx?editors=1111

Note that `getShadowRoot` should be set to `true` in your case, since you don't have any closed shadows. What you had before, `getShadowRoot: () => this.shadow`, was always returning your shadow root no matter what `node` was passed to the function, which is why your trap was broken. See the docs here: https://github.com/focus-trap/tabbable?tab=readme-ov-file#getshadowroot-option

So now, with the tweaked pen, at first, you don't see the modal.

When you click on the "open modal" button, you'll see that only the modal has the focus outline. __However__, the first "Button from shadow DOM" button actually has focus: Just press Enter or Spacebar and you'll see "shadow click" printed to the console.

And once you do, Chrome will finally put a default blue outline around the button:

<img width="365" alt="image" src="https://github.com/user-attachments/assets/0d4d212c-3214-4694-8c1e-21318c0ae5be">

Then you tab and go to the "Button from light DOM" button, where you can press Enter again and see "light click" in the console.

So that first button, even though in a shadow DOM, __is__ focused first after all. Focus-trap  (and Tabbable, internally) is doing the right thing.

Since things appear to be behaving like they should (at least from Focus-trap's point of view), I'm going to close this issue. But if there's still a problem, we can re-open it.

**Comment by bakura10** [comment]
Hi !

Thanks a lot for the clarification @stefcameron . Indeed it seems that setting getShadowRoot: true was part of the solution. I appreciate the time you spent on this. If I face extra issues I will try to open a bug to Chrome directly.
