### ISSUE TITLE
Remove source map files from dist?

### ISSUE THREAD

**Issue by tomasvn** [focus-trap/focus-trap#1308]
- I can see that source map files are included in dist and then are publish all together

- My question are source maps needed to published? If removed all together, it could save some install size

**Comment by stefcameron** [comment]
> My question are source maps needed to published? If removed all together, it could save some install size

They are so that consumers can debug the distribution code.

I'm not really concerned about the installation size on disk when `npm install`-ing the package. What's more important is the runtime size when you want to incorporate Focus-trap into a web app (i.e. how much will the app's bundle size increase by importing Focus-trap).

Do you have a different perspective?

**Comment by tomasvn** [comment]
Fair, point, I might have tought that source maps are included in the final bundle? I might be reading too much into it, and in the end, it might be nothing. Running it through [https://pkg-size.dev/](https://pkg-size.dev/) seems correct. So it is indeed without everything just the final build.
