### ISSUE TITLE
Competing focus trap - range call stack error

### ISSUE THREAD

**Issue by tomasvn** [focus-trap/focus-trap#1319]
![image](https://github.com/user-attachments/assets/9e9fd860-d254-404c-9b21-354ed8b52cb5)

I am currently using `focus-trap v7` with `useFocusTrap` from vue use, it behaves correctly when I use it on my own modal, issue arises when it competes with other focus trap implementation, the other focus trap actives on 3rd party modal, that I have no control over, is there any solution?

**Comment by stefcameron** [comment]
@tomasvn The stack trace image you provided doesn't show much context, unfortunately. Without knowing where the error is, and so what is blowing the stack, the only thing I could say is you might need to use the `trapStack` option in this case -- but that's assuming you can set Focus-trap options on both your own use via `useFocusTrap`, as well as on that third-party library that activates the modal and uses Focus-trap.

That said, the option may not really do anything since that's more for having two separate instances of Focus-trap share the same stack so that they can properly share in pausing/activating themselves.

Without using this option, I would expect some conflict in terms of fighting for focus, but not a `call stack exceeded` exception... 🤔

**Comment by tomasvn** [comment]
@stefcameron I did find a similiar issue, here https://github.com/twbs/bootstrap/issues/39258 , I'll try to provide more info, once I'll debug it more, or rather try to active it somehow separately.

**Comment by tomasvn** [comment]
@stefcameron I can see that 3rd party is using this library, the range callstack error, pointed me to this https://github.com/focus-trap/focus-trap/blob/f85c73ac36553d952a8e03d1033b35544247caa0/index.js#L466 line

not sure if this is this would help

**Comment by stefcameron** [comment]
@tomasvn Thanks for identifying the offending line. I think the issue you pointed to earlier in the `twbs/boostrap` library gives a pretty good account of what's happening, that being their library and Focus-trap, both being initiated at the same time, end-up fighting each other "to the death", as it were, for the input focus, stealing it from one another until Focus-trap finally blows its call stack as it reacts to changes in focus when the other library tries to steal it away after Focus-trap tries to take it back, and so on...

Assuming that's the case, and assuming `twbs/boostrap` doesn't employ Focus-trap internally to manage the focus, then the shared `trapStack` option wouldn't be of much help.

The only thing that would (probably) work is if `twbs/bootstrap` exposed an API on its trap to pause it, like Focus-trap does, so that you could pause their trap before you activate your Focus-trap, and vice-versa.

**Comment by tomasvn** [comment]
@stefcameron I think I am not able to solve it, the 3rd party modal, is using your package under the hood, I have no control over it what so ever, I am left to not using trapping mechanism at all, which is bad.

**Comment by stefcameron** [comment]
I wish I could help somehow, but the `trapStack` option is the best answer that Focus-trap has to address the case where multiple instances of Focus-trap are created in the same DOM. You should open an issue on that third-party library that also uses Focus-trap to request that they expose some or all of the underlying Focus-trap options (particularly `trapStack`, assuming it would indeed fix the issue).

**Comment by stefcameron** [comment]
Since Focus-trap provides `trapStack` which I believe would resolve this issue, but the third-party does not expose it, I'm going to close this issue. If there's something that comes up that Focus-trap could do more, then we can certainly re-open it. I hope the third-party can help out! 🙂

**Comment by SnippetsUnlimited** [comment]
I reported this issue in Oct 2023 here [https://github.com/twbs/bootstrap/issues/39258](url)

I have a very valid use case where no third party usage is involved. To work with multiple BS Modals where one modal stacks on top of each other. the Focus Trap in the previous modal messes up the Modal on the top.

Can BS focusTrap be at least exposed if activation/deactivation is a big deal, so that we can use it with trapStack like you suggested?

**Comment by stefcameron** [comment]
@SnippetsUnlimited That would be up to the maintainers of Bootstrap FocusTrap. I don't know what that project is; it's not something I manage, and it's not this repo. I recommend you try to get their attention in their repo, or maybe submit a PR and see if they'll take it, or worst case, fork their repo and fix it yourself in a new package you'd publish from your fork (hopefully doesn't come to that!).

**Comment by tomasvn** [comment]
Adding this comment if anyone will encounter the issue.

We had to define custom global variable on a window `window.__focusTrapStack = []` and use this variable inside the options for `trapStack` with defining custom stack, the issue reported was resolved.
