### ISSUE TITLE
Bootstrap Modal Dialogue and Bootstrap Datepicker

### ISSUE THREAD

**Issue by ashefer1** [focus-trap/focus-trap#250]
I have a datepicker on the bootstrap modal dialogue. Focus-trap doesn't work.  It works fine when I remove the datepicker control.

**Comment by stefcameron** [comment]
Thanks for letting me know! Could you be a bit more specific about exactly what isn't working? Have you done some debugging to figure out why it's not working?

Please also provide a codesandbox.io sample that reproduces the issue.

**Comment by ashefer1** [comment]
Thank you for your reply. Please see https://codesandbox.io/s/priceless-dirac-shyt8 .
You can open the modal with and without the datepicker and observe the problem.
I haven't debugged yet.

**Comment by stefcameron** [comment]
That's interesting! The "toggle date picker" just dismisses the modal instead of adding/removing the date picker. But without clicking that button, what I see is that the trap appears to work on the first forward cycle through the tab sequence in the modal, but once it loops back around to the close (X) button, something breaks and focus escapes. I also see that the two main modal buttons aren't part of the tab sequence the first time around, though they appear to be within the trap's container. Are they supposed to be in or out of the trap?

**Comment by ashefer1** [comment]
The buttons are inside the trap container. Clicking the button hides the datepicker and dismisses the modal so you can start over without the datepicker and see that it works perfectly. I guess running it in the sandbox causes some weird effects on its own. 
It works much cleaner when I run it as a standalone html file.

**Comment by ashefer1** [comment]
It can be closed. The bug is in the bootstrap datepicker.  focus-trap is perfect.

**Comment by stefcameron** [comment]
> It can be closed. The bug is in the bootstrap datepicker. focus-trap is perfect. While debugging the focus trap I saw that
> the deactivate method got called. The datepicker calls the modal dialog hide.bs.modal handler and deactivates the focus-trap.

Great news! I appreciate you circling back here and letting me know. 🎉  Closing.
