### ISSUE TITLE
Wait child focus before call onActivate callback

### ISSUE THREAD

**Issue by germsb** [focus-trap/focus-trap#395]
Hi, thanks for your library, it help me alot.

Actualy if we deactivate trap during the onActivate callback like this,
```js
const trap = createFocusTrap(container, {
        returnFocusOnDeactivate: false,
    });
    trap.activate({
        onActivate: () => {
            trap.deactivate()
        },
    });
```
the first focusable elem in container dont get focus.

As workaround, we must enclose the deactivate function  with a setTimeout which is not advised.
```js
//...
trap.activate({
        onActivate: () => {
            setTimeout(trap.deactivate, 5);
        },
})
//...
```

**Comment by stefcameron** [comment]
@germsb Thanks for using focus-trap, I'm glad it's helped you out!

Can you explain more about your use base for deactivating the trap as soon as it's activated? That doesn't seem like a normal thing to need to do. Under what circumstances are you needing to cancel activation, and is there not a way you can prevent the trap from getting activated? The trap is inactive after creation, so the only way it's getting activated is because your code is calling `trap.activate()`, so is there not a way you can prevent your code from calling that method if the trap shouldn't be activated?

**Comment by germsb** [comment]
It is a slightly diverted use.  Usually I use the focus-trap normally but sometimes I just need to find the first focusable element without locking the focus inside an element and this library has everything to do it without having to rewrite some code.

**Comment by stefcameron** [comment]
Ah, OK, thanks for explaining that. Sounds like you should be using `tabbable` directly, in that case. `focus-trap` uses the `tabbable` library (also part of the @focus-trap org) to determine what nodes are tabbable (and therefore, focusable) in any container(s) you give to `createFocusTrap()`.

I think `tabbable` will give you all the features you need to determine the first focusable node...

**Comment by germsb** [comment]
I agree, tabbable looks perfect for this, I will use it right now! However, shouldn't the OnActivate callback be triggered once the focus is set on the first focusable / tabbable node?

**Comment by stefcameron** [comment]
> I agree, tabbable looks perfect for this, I will use it right now!

Awesome!

> However, shouldn't the OnActivate callback be triggered once the focus is set on the first focusable / tabbable node?

I hear what you're saying, and I'd be tempted to make that change, but I think it's been like this (`onActivate()` fires just before the initial focus node is focused) for longer than I've been the maintainer of the project, and with the number of projects out there using `focus-trap`, I think it's just the way it is... I'm concerned if I change it because it seems like the right thing do, it'll break someone else's expectations.

So my suggestion would be to add a new event, like `onPostActivate()`, that gets called after the initial focus node has been focused, and all of `focus-trap`'s activation is done. So that would be [right here](https://github.com/focus-trap/focus-trap/blob/1baf62e20f18370f3852e7f0b636052aa91063e7/index.js#L488) just before returning, because the focus happens in `addListeners()`.

**Comment by germsb** [comment]
It seems like a good compromise! Thanks for the time spent on this

**Comment by stefcameron** [comment]
Closing very old issues. If it's still an issue with the current release, feel free to re-open.
