### ISSUE TITLE
Allow audio as last element

### ISSUE THREAD

**Issue by Anubarak** [focus-trap/focus-trap#419]
Is there any trick to allow audios as last elements via focus trap?
I have a hard time to make it working and I still don't know what I'm doing wrong.

Here is an example Sandbox https://codesandbox.io/s/affectionate-blackwell-o700p?file=/index.html

Scenario:
Click on "enable trap" 
Try to tab something inside the audio control (volume bar or something) and modify it via keyboard.

Expected Behavior: 
you can change the volume

Actual Behavior:
There is no way to tab to the volume bar.

Is there some tricky hacky way (even forking your lib) to make this working? I already use a custom version because you don't support `iFrames` and I had to add it as a custom tabbable selector.

Thank you very much for your work. Beside that your Library is awesome

Edit: or at least an easy way in the plugin to change the focus to the first item, when you focus a "placeholder" item.

**Comment by stefcameron** [comment]
👋 Hi! Thanks for asking.

> I already use a custom version because you don't support `iFrames` and I had to add it as a custom tabbable selector.

But we do support `iframe` elements, tabbing in and out of them: https://focus-trap.github.io/focus-trap/#demo-iframe

Does that not work for you?

> Here is an example Sandbox https://codesandbox.io/s/affectionate-blackwell-o700p?file=/index.html

Thank you. Very helpful!

> Scenario:
> Click on "enable trap"
> Try to tab something inside the audio control (volume bar or something) and modify it via keyboard.
> 
> Expected Behavior:
> you can change the volume
> 
> Actual Behavior:
> There is no way to tab to the volume bar.

So focus-trap does support Audio `<audio controls>` and Video `<video controls>` elements, because [tabbable supports them](https://github.com/focus-trap/tabbable/blob/66c7a6945014fe175e57c7c8acccb270643c2857/src/index.js#L8-L9) (focus-trap gets its list of tabbable elements from that sibling library).

And as you can see in your sandbox, we do let you tab to it, but we don't _inside_ because those individual buttons are actually part of the Shadow DOM, not the Light DOM.

![image](https://user-images.githubusercontent.com/2855350/121264461-c3b74580-c87c-11eb-96f2-bd61dc377707.png)

We are currently working on adding Shadow DOM support to tabbable: https://github.com/focus-trap/tabbable/pull/304 Once that's done, as long as this shadow root is open (not closed), you'll be able to tell tabbable about it so that we can go inside and look.

FYI @idoros

**Comment by idoros** [comment]
> So focus-trap does support Audio <audio controls> and Video <video controls> elements, because tabbable supports them

Not so much, tabbable recognize that an audio/video element with controls is focusable, but it has no access to the inner controls. I don't think there is a way to access them with javascript. That is a limitation of the browser.

> We are currently working on adding Shadow DOM support to tabbable: focus-trap/tabbable#304 Once that's done, as long as this shadow root is open (not closed), you'll be able to tell tabbable about it so that we can go inside and look.

This solution will not solve audio/video inner controls, because although they may be implemented as shadow dom in some browsers, this shadow dom is not accessible (user-agent shadow dom is what the dev tools say).

> > I already use a custom version because you don't support iFrames and I had to add it as a custom tabbable selector.
>
> But we do support iframe elements, tabbing in and out of them: https://focus-trap.github.io/focus-trap/#demo-iframe

Tabbable doesn't go into Iframes, it might be able to traverse into accessible iframes from the same domain (like open shadow root) with the new shadow dom mechanism, but not into closed ones.

@Anubarak, The issue you encountered is a known limitation of focus-trap, In the documentation of focus-trap it say [`Use predictable elements for the first and last tabbable elements in your trap`](https://github.com/focus-trap/focus-trap#use-predictable-elements-for-the-first-and-last-tabbable-elements-in-your-trap), that is because focus-trap works with the first and last elements of a trap container. Anything focused between them is not checked, so in your case adding a normal input after the audio element and within the container would allow you to tab the inner audio controls.

**Comment by idoros** [comment]
@Anubarak you say you needed to add a custom tabbable selector to the builtin list, may I ask which one?

**Comment by Anubarak** [comment]
Thank you very much for your fast answers :)

> @Anubarak you say you needed to add a custom tabbable selector to the builtin list, may I ask which one?

I added `iFrame` to the list. It is the same issue mentioned above, but when I add `iFrame` I can navigate here https://codesandbox.io/s/blissful-proskuriakova-ivgp4?file=/index.html
unfortunately I wasn't able to just include the modified script in that demo, so this is with your original package.

After I added `iFrame` I can navigate in the youtube window with an active trap.

> But we do support iframe elements, tabbing in and out of them: https://focus-trap.github.io/focus-trap/#demo-iframe

You are totally correct. Sorry about this one... This is again my fault v.v. It's really only an issue when the iFrame is the last element (it is mentioned in the docs and instead of reading and understanding them properly I modified the source code and noticed it worked by adding `iFrame`). Sorry again for the trouble.

Is there any good known solution yet?
I can think of adding a `<div>` at the end of each trap and add `tabindex=0` to it in order to skip to the first element or the item before that div (depending if you go backward or forward) via `onFocus` event.

Again thank you for your incredible fast replies and sorry for not reading properly before creating this issue.

**Comment by idoros** [comment]
> I added iFrame to the list

Doing that will stop on every iframe element regardless of its content because it is focusable, but not tabbable by default. 

> Is there any good known solution yet?

You can achieve the same result by adding `tabindex=0` to the last/first iframe element (can be easily automated when running `trap.activate()`). Unfortunately that will add a step, focusing the iframe, in the tabbing process (same as result as adding the iframe to the list).

You should also know that none of these solutions is perfect, tabbing backwards (shift+tab) when the last element is an iframe will skip the iframe content and focus on the iframe itself, and the then another backwards tab will take you to the element before that iframe.

I had a project once in which I built special edge components that would be placed on the start and end of a popup and would inform the user that they are at the edge of a popup and would move the focus between them, or give the user the ability to normal tab into the browser interface. I don't remember the product details, but that solution worked well for that product, and might not be suitable everywhere.
