### ISSUE TITLE
Focus trap infinite looping because of focusing programatically an element from outside the trapped container

### ISSUE THREAD

**Issue by carlesnunez** [focus-trap/focus-trap#428]
Hi all, I'm experiencing a performance problem when using focus-trap given the next conditions:
1. I have an element in react that is a dropdown which,  on getting oppened, render a full screen layer to show the dropdown options. This layer is outside the "trapped" container.
2. When opening that layer I perform an autofocus on the first element of the dropdown for A11Y purposes.
3. As this element is outside the trapped element it goes through this code:
```javascript
  var checkFocusIn = function checkFocusIn(e) {
    var targetContained = containersContain(e.target); // In Firefox when you Tab out of an iframe the Document is briefly focused.

    if (targetContained || e.target instanceof Document) {
      if (targetContained) {
        state.mostRecentlyFocusedNode = e.target;
      }
    } else {
      // escaped! pull it back in to where it just left
      e.stopImmediatePropagation();
      tryFocus(state.mostRecentlyFocusedNode || getInitialFocusNode());
    }
  };
```
And here is where the problem starts. As the element is outside of the targetContainer it fallback to the else. Going to the most recently focused element, which in this case is the element that, on focus, will trigger an automatic on focus to the input from teh modal, that as we said, is outside of the targetContainer and it will again, over an over try to "tryFocus" putting me into an infinite loop.

Is there a way to avoid a situation like this one?

**Comment by stefcameron** [comment]
Hi, @carlesnunez! 👋 Thanks for asking.

First thought: Since the dropdown options are displayed in a modal, even if the trap is paused, focus shouldn't be going anywhere else anyway, so [pause the trap](https://github.com/focus-trap/focus-trap#trappause) when the dropdown's list is displayed, and [unpause the trap](https://github.com/focus-trap/focus-trap#trapunpause) when the selection is made and the modal layer showing the dropdown options is removed.

**Comment by carlesnunez** [comment]
Given the architecture in which I'm working with, the piece of code opening the dropdown doesn't have access to focus-trap instance so I cannot pause the trap :(

**Comment by stefcameron** [comment]
So your code isn't also the owner of the trap? The only other thing I could think of is using the multi-container option, whereby you can give more than one container to the trap when you create it, and you can also [update the containers](https://github.com/focus-trap/focus-trap#trapupdatecontainerelements) while the trap is active. So when then dropdown list modal appears, call `trap.updateContainerElements()` to add the modal as a container in the trap.

Otherwise, if you're not controlling the trap, I'm not sure there much you can do, unless you can figure out a way to make your modal a child of the trap but still have a full screen appearance using some CSS tricks.

**Comment by stefcameron** [comment]
Open for a while without response. Closing. Feel free to re-open if you're still having trouble with it.
