### ISSUE TITLE
🐛 first trap deactivates second trap 

### ISSUE THREAD

**Issue by far-fetched** [focus-trap/focus-trap#441]
### **Steps** to reproduce the problem 

(might be difficult as it is not deterministic - combination with emberJS framework)

- first trap is active,
- second trap is activating (try focus with delay - [code](https://github.com/focus-trap/focus-trap/blob/master/index.js#L429))
- variable `activeFocusDelay` with timeout id of second focus trap is visible for all traps <---- important !
- first trap is deactivated (it cleans existing timeout) [code](https://github.com/focus-trap/focus-trap/blob/master/index.js#L523)
- as variable `activeFocusDelay` is shared and pointed out to second trap focus function, it is not executed.

### **What went wrong?**

- element from second trap is not focused

### **Possible solution**

-  as variable `activeFocusDelay` is not used outside of function `createFocusTrap` it can be moved inside that function.

Is it intentional to keep this variable out of `createFocusTrap` function ? If yes, why ? Please give any feedback. Thanks in advance

**Comment by stefcameron** [comment]
Hi, @far-fetched 👋 ,

> Is it intentional to keep this variable out of `createFocusTrap` function ? If yes, why ? Please give any feedback. Thanks in advance

Thanks for the inquiry/bug report. I've been the maintainer for focus-trap for about a year now, so I don't have full history, and the addition of this delay predates me by at least a year. I found #83 which is when the `clearTimeout()` was added, back on May 19, 2019.

So, AFAICT, there's no good reason why it's a global, and not trap-specific. Sure seems to make sense that it be trap-specific to avoid this race condition where the second trap doesn't get initial focus because first trap deactivation clears the timer.

**Comment by stefcameron** [comment]
@far-fetched I opened #447 to fix this, but our `no-delay` demo, which activates a second trap while the first is active, doesn't appear to suffer from this race condition. Would be great if you could pull the PR and try it locally with `yarn link` or `npm link` and LMK if it's solving the problem.

**Comment by stefcameron** [comment]
This is being published in 6.6.0 right now.
