### ISSUE TITLE
Demo site links are broken

### ISSUE THREAD

**Issue by Dan503** [focus-trap/focus-trap#489]
I went to go look up how to do the `checkCanFocusTrap` pattern but all the demo source code links are broken.

I can't see the demos in the repo any more, where did they go?

https://focus-trap.github.io/focus-trap/

**Comment by stefcameron** [comment]
🤔 All the "view demo source" links are working for me... except for the "Animated Dialog" sample one, which goes to this 404: `https://github.com/focus-trap/focus-trap/blob/master/docs/js/animated.js` -- and that's because the JS file is named `animated-dialog.js`, not `animated.js`.

So maybe that file got renamed at some point during that PR and we just forgot to update the "view source" link?

I don't recall renaming the file since that PR.

I fixed the link: https://github.com/focus-trap/focus-trap/commit/963813a71687e71218bd2afdf51dfd4086a9ba2b

Should get deployed in a few minutes.

**Comment by stefcameron** [comment]
It's deployed. Should work now. 😄 Thanks for alerting me to the broken link.

**Comment by Dan503** [comment]
Oh, I didn't test all the links.

I went to the one link that was broken and assumed it was the same case for all of them.

I should have probably opened at least one more link before saying they were all broken 😅

**Comment by stefcameron** [comment]
Aha! 😉 Well, at least we got that link fixed.
