### ISSUE TITLE
Problem inside shadow dom

### ISSUE THREAD

**Issue by andersthorsen** [focus-trap/focus-trap#496]
Hello!

Consider a `<div>` to which a shadow dom is attached. 

If I then add elements below this and use focus-trap for a child element (modal dialog im my case) the click event on the shadow dom will trigger for all those child elements and the event will be cancelled by this code:

```
  var checkClick = function checkClick(e) {
    if (valueOrHandler(config.clickOutsideDeactivates, e)) {
      return;
    }

    if (containersContain(e.target)) {
      return;
    }

    if (valueOrHandler(config.allowOutsideClick, e)) {
      return;
    }

    e.preventDefault();
    e.stopImmediatePropagation();
  }; //

```

If I change
`    if (containersContain(e.target)) {
`
to
`    if (containersContain(e.path[0])) {
`
it works.
path[0] will always be the actual clicked event, while the target in this case is the shadow dom parent.

**Comment by stefcameron** [comment]
Hello! Would you mind re-editing your post here? It looks a bit mangled, and it's difficult to follow.

Concerning `event.path[0]`: I don't see a `path` property on the DOM Event object: https://developer.mozilla.org/en-US/docs/Web/API/Event Am I missing something?

focus-trap doesn't work well with the Shadow DOM at the moment. That's likely in big part because tabbable, the dependency it uses to determine what's tabbable, doesn't work with the Shadow DOM either. There's an effort to rectify that to a certain extent, however: https://github.com/focus-trap/tabbable/pull/304

**Comment by andersthorsen** [comment]
> Hello! Would you mind re-editing your post here? It looks a bit mangled, and it's difficult to follow.

Done. Hoper it's easier to read now

> 
> Concerning `event.path[0]`: I don't see a `path` property on the DOM Event object: https://developer.mozilla.org/en-US/docs/Web/API/Event Am I missing something?

You're correct. I seems I looked at a Chromium-only property when I debugged this. The standardized variant is [composedPath ](https://developer.mozilla.org/en-US/docs/Web/API/Event/composedPath)

> 
> focus-trap doesn't work well with the Shadow DOM at the moment. That's likely in big part because tabbable, the dependency it uses to determine what's tabbable, doesn't work with the Shadow DOM either. There's an effort to rectify that to a certain extent, however: [focus-trap/tabbable#304](https://github.com/focus-trap/tabbable/pull/304)

Interesting. And great news that they are working on the issue.

The code I refer to above makes it completely unusable tough, not just buggy as at least in my case it considers all clicks within my window as being outside. (the shadow root host element also getting a click in addition to the button placed inside)

**Comment by stefcameron** [comment]
@andersthorsen Thanks for clarifying the text in the description.

OK, so `event.composedPath()[0]` would fix things for your open-shadow use case. But what of `event.target`, then? What's the relationship between `event.target` and the array returned by `event.composedPath()`? My assumption would've been that `event.target` would always point to the first element in the path, but that can't be true, because if it did, then you wouldn't be having this problem because `event.target === event.composedPath()[0]`.

So does `event.composedPath()` only return an array IIF the click originated inside a shadow root? The docs don't indicate such an exception.

`composedPath` is also a newer API, so it seems the code would need to change to something like this:
```javascript
const actualTarget = typeof event.composedPath === 'function' ? event.composedPath()[0] : event.target;
if (containersContain(actualTarget)) {
  return;
}
```

But because `event.target !== event.composedPath()[0]`, I'm concerned about the ramifications on everyone else using this library who isn't using it around a shadow root.

**Comment by andersthorsen** [comment]
My understanding is that the inner most element that is clicked is event.composedPath()[0] always, but target for a shadow dom host element will be the host element and not the inner element.

event.composedPath()[0] will then point to the inner element (e.g. button inside shadow dom) while event.target points to the element hosting the shadow dom (e.g. a <div>) which is somewhere in that path.

At least that is what my googling tells me, and it corresponds with my debugging as well.

You can see a codepen demonstrating this here:
https://codepen.io/andersthorsen/pen/rNwmLBV

**Comment by stefcameron** [comment]
Thanks for the info. Then in that case, the condition on whether to use `event.composedPath()[0]` or `event.target` would have to be based on whether `event.target` is an open shadow root or not, right?

So this (to also be compatible with older browsers that don't support `event.composedPath`):
```javascript
const actualTarget = (event.target.shadowRoot && typeof event.composedPath === 'function') ? event.composedPath()[0] : event.target;
if (containersContain(actualTarget)) {
  return;
}
```

**Comment by andersthorsen** [comment]
Your solution looks good to me.

But: If the purpose is to prevent clicks outside the target, why not just return if actualTarget != this?

The reasoning here being that if the event bubbled (to the div in the sample) up from a child element (actualTarget != this) the test was already done for the actual target (in the sample the buttons)? Why waste processing time doing this check for every single parent the event bubbles up to?

**Comment by stefcameron** [comment]
I'm not quite following you about just returning if `actualTarget !== this`: What is `this`? Seems like it would be the trap itself, but the trap isn't an element. `checkClick` gets called _on capture_ when there's a click anywhere in the document, not on bubble, and the trap could have multiple containers, so we have to see if the element that was clicked is part of any of those containers. You can't click the trap itself, since the trap isn't any one thing.

If the trap has a single container, then I suppose you could argue that this container is what you could check, like `if (actualTarget === containers[0]) then return`, but we're using the `contains()` API, which I believe is quite efficient, so the overhead of looping over a single element array should be negligible.

Now this logic of using `composedPath` instead of `target` when there's a shadow root, do you think it needs to be used _everywhere else_ we use the `event.target`? What about using the Tab key inside your shadow root. That's working fine as-is?

**Comment by stefcameron** [comment]
> Now this logic of using `composedPath` instead of `target` when there's a shadow root, do you think it needs to be used _everywhere else_ we use the `event.target`? What about using the Tab key inside your shadow root. That's working fine as-is?

I did my own testing. It doesn't work fine. We need to use `composedPath()` everywhere we currently use `event.target`. Otherwise, tabbing doesn't work either.

**Comment by andersthorsen** [comment]
Thanks for looking into this. I haven't had time to do my own tests yet but I'll try to pull the branch early next week and see if that resolve the issues.

**Comment by stefcameron** [comment]
> Thanks for looking into this. I haven't had time to do my own tests yet but I'll try to pull the branch early next week and see if that resolve the issues.

That would be great, thanks!

**Comment by stefcameron** [comment]
@andersthorsen FYI, I managed to get my PR working. I think it works well, for both mouse and tab key. I will publish this in the next few days, as early as Saturday.

**Comment by stefcameron** [comment]
> Thanks!
> 
> I pulled the branch shadow-dom and repaced the content of the node module installed and it worked :)
> 
> Really appreciate this.

Wonderful, thank you! My pleasure. I will get this published, then!

**Comment by stefcameron** [comment]
@all-contributors add @andersthorsen for bug
