### ISSUE TITLE
Can't interact with elements outside of the container tree

### ISSUE THREAD

**Issue by psmyrdek** [focus-trap/focus-trap#87]
Hello!

**Description**

I have a form that works as a focus trap container, and inside of it I have an input which works as a location picker root (using Google Maps Autocomplete Widget):
```
Document:
-------------------------
|  focus trap container |
|  [autocomplete]       |
-------------------------
[google autocomplete results]
```
The problem is that the dropdown with results that Google widget produces is appended to the page outside of the container, and later positioned `absolute`ly to sit exactly below the input:

![image](https://user-images.githubusercontent.com/6187417/59445243-92c3e780-8dff-11e9-909a-d104997a979b.png)

The current implementation of this lib makes it impossible to select dropdown elements, because handler for click looks like that:
```js
  function checkClick(e) {
    if (config.clickOutsideDeactivates) return;
    if (container.contains(e.target)) return; // => false
    e.preventDefault();
    e.stopImmediatePropagation();
  }
```
Second condition isn't meet because dropdown actually sits *outside* of the container, but from the user's perspective, it's still the same form one would like to interact with. As a result, you can't pick items from this dropdown.

**Comment by psmyrdek** [comment]
@davidtheclark I'd like to create PR fixing this issue, but could you suggest preferred way of fixing it? I was considering if maybe passing a list of whitelisted elements of this kind into options object would help here? Or maybe you have some better ideas?

**Comment by dougalg** [comment]
Would the "correct" solution not be to ensure that DOM elements are logically ordered? Ie that the dropdown appears within the container, rather than at root level? IMO this sounds like an accessibility bug in Google's implementation.

**Comment by psmyrdek** [comment]
They solved it by capturing keyboard events when the dropdown is opened, so the end user knows nothing about the incorrect placement in the DOM tree. Everything works fine on their end - you start typing, the dropdown appears, and you can select items using keyboard navigation.

Another hack people suggest to solve it is as follows:
1. Load google autocomplete lib
2. `<div class="pac-container"></div>` is being added to the body
3. Programmatically move this container to the place within focus trap container
4. Focus trap no longer blocks it, but styling of the dropdown itself is broken :/ 

I'd rather whitelist containers outside of the focus trap root to support cases like this one.

**Comment by jack-sf** [comment]
Instead of passing some list, I think the best future solution would be to just allow the user to define a function that can say "should I block focus for this click?".

Something similar to https://github.com/willmcpo/body-scroll-lock#allowtouchmove .

So we could add a parameter `allowOutsideClick(event: MouseEvent)` to `createOptions` ( https://github.com/davidtheclark/focus-trap#focustrap--createfocustrapelement-createoptions ).

Although, I agree with @dougalg, that sometimes it might be a big code/DOM-smell.

Another question: If you let somebody click on an element outside of the DOM tree, the focus will jump to that element. Will focus trap still work then (shift-tab / tab should lead back to the focus trap)? That's something that would need to be checked while implementing this `allowOutsideClick` as well.

**Comment by jtomaszewski** [comment]
Instead of passing some list, I think the best future solution would be to just allow the user to define a function that can say "should I block focus for this click?".

Something similar to https://github.com/willmcpo/body-scroll-lock#allowtouchmove .

So we could add a parameter `allowOutsideClick(event: MouseEvent)` to `createOptions` ( https://github.com/davidtheclark/focus-trap#focustrap--createfocustrapelement-createoptions ).

Although, I agree with @dougalg, that sometimes it might be a big code/DOM-smell.

Another question: If you let somebody click on an element outside of the DOM tree, the focus will jump to that element. Will focus trap still work then (shift-tab / tab should lead back to the focus trap)? That's something that would need to be checked while implementing this `allowOutsideClick` as well.

**Comment by stefcameron** [comment]
Closing issues older than 2020. Please LMK if this is still a problem.
